name: master builder

on:
  pull_request:
  push:
    branches: [ master ]
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/master.yml'

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Golang env
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: false # conflict with golangci-lint cache
      - name: lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
  build-and-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Golang env
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
      - name: Install Ginkgo
        run: go install github.com/onsi/ginkgo/v2/ginkgo
      - name: Build
        run: go build
      - name: Unit Test
        run: go test -v $(go list ./... | grep -v /test) # skip e2e test
      - name: E2E Test
        run: ginkgo -v -r ./test
